// <auto-generated />
using System;
using Cocoloko.Storing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cocoloko.Storing.Migrations
{
    [DbContext(typeof(CocolokoDbContext))]
    [Migration("20200928003132_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cocoloko.Storing.Models.Beverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Beverage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "irish car bomb",
                            Price = 8.5
                        },
                        new
                        {
                            Id = 2,
                            Name = "jaggerbomb",
                            Price = 7.0
                        });
                });

            modelBuilder.Entity("Cocoloko.Storing.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeverageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BeverageId");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeverageId = 1,
                            Name = "baileys",
                            Price = 1.5
                        },
                        new
                        {
                            Id = 2,
                            BeverageId = 1,
                            Name = "guinness",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 3,
                            BeverageId = 1,
                            Name = "jameson",
                            Price = 2.0
                        },
                        new
                        {
                            Id = 4,
                            BeverageId = 2,
                            Name = "jagger",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 5,
                            BeverageId = 2,
                            Name = "red bull",
                            Price = 3.0
                        });
                });

            modelBuilder.Entity("Cocoloko.Storing.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Cocoloko.Storing.Models.Beverage", b =>
                {
                    b.HasOne("Cocoloko.Storing.Models.User", null)
                        .WithMany("Beverages")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Cocoloko.Storing.Models.Ingredient", b =>
                {
                    b.HasOne("Cocoloko.Storing.Models.Beverage", "Beverage")
                        .WithMany("Ingredients")
                        .HasForeignKey("BeverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
